### ISSUE TITLE
JsonException

### ISSUE THREAD

**Issue by AmbroiseCouissin** [aws/aws-dotnet-trace-listener#1]
Hi,

I'm using the sample you gave and those are the errors that I get:
Exception thrown: 'ThirdParty.Json.LitJson.JsonException' in AWSSDK.Core.dll
{"Can't assign null to an instance of type System.IO.MemoryStream"}

It was triggered by DynamoDbTraceListener.cs:630: map = JsonMapper.ToObject<Dictionary<string, AttributeValue>>(line);

I solved it by using Document doc = Document.FromJson(line); instead.

But when I solve the issue, i get this one when executing the batch:
{"Key attribute Origin must be a Primitive type"}

Cheers,
Ambroise

**Comment by PavelSafronov** [comment]
Thanks for reporting this. It appears to be an issue with the underlying LitJson implementation which we use for deserializing JSON. We're looking into this.

**Comment by AmbroiseCouissin** [comment]
Thanks.

In the meantime I've written my version of a DynamoDbTracer. 

I would suggest the drop of Amazon utilities and use Newtonsoft Json instead.
I would also suggest to not use files to store logs but just doing it in memory.
Finally, the only apis from DynamoDb that should be used are those:
BatchWrite.AddPutItems(_logToBeUploaded);
BatchWrite.ExecuteAsync());

It would greatly reduce the complexity and the code base. It would also be faster and async.

**Comment by PavelSafronov** [comment]
We've released a patched version of Core and AWS.TraceListener which requires this latest version of Core.

Your version of DynamoDbTracer sounds like a good approach, especially using Newtonsoft Json. However, keep in mind that we chose to use file storage because it allows offline tracing, as well as allows log recovery in the event of an application/system crash.

**Comment by AmbroiseCouissin** [comment]
I see. It makes sense. I'm just allergic to files hahaha.

Thanks for your help!
