### ISSUE TITLE
It doesn't support the latest version of awssdk.core

### ISSUE THREAD

**Issue by kckc** [aws/aws-dotnet-trace-listener#3]
I don't think there is anything that needs to be changed right? It just need to say that it support the latest version in the nuget package.

**Comment by ashishdhingra** [comment]
Hi @kckc,

Good afternoon.

This appears to be fixed in the latest version as part of commit https://github.com/aws/aws-dotnet-trace-listener/commit/10eb0479ed3653efda5c7e1490153a489aa90281. Closing this issue.

Thanks,
Ashish
